SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for simple_job
-- ----------------------------
DROP TABLE IF EXISTS `simple_job`;
CREATE TABLE `simple_job` (
  `simple_job_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_name` varchar(50) NOT NULL COMMENT '任务名称',
  `status` bigint(20) DEFAULT '-1' COMMENT '状态，-1永远执行，0 不再执行  1执行并减1执行一次少一次',
  `description` varchar(1000) DEFAULT NULL COMMENT '描述',
  `source_type` varchar(50) NOT NULL COMMENT '数据源类型，mysql,hive',
  `source_db` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '来源数据源类型',
  `select_sql` varchar(5000) NOT NULL COMMENT '查询SQL',
  `check_exist_sql` varchar(1000) NOT NULL COMMENT '校对记录是否存在',
  `update_sql` varchar(5000) NOT NULL COMMENT '修改SQL',
  `insert_sql` varchar(5000) NOT NULL COMMENT 'insert SQL',
  `execute_order` int(11) NOT NULL COMMENT '执行顺序',
  `error_go_on` varchar(255) NOT NULL COMMENT '异常是否继续,Y 继续，N 不再接下去进行',
  `parent_job_name` varchar(255) NOT NULL COMMENT '依赖父任务',
  `gmt_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `gmt_create` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 未删除， 1 已删除',
  PRIMARY KEY (`simple_job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8 COMMENT='job记录表';

-- ----------------------------
-- Records of simple_job
-- ----------------------------
BEGIN;
INSERT INTO `simple_job` VALUES (16, '_user_daily_init', 0, '每日门店新增客户', 'auto_mysql', 'oldmain', 'SELECT tenant_id, DATE_FORMAT(gmt_create,\'%Y-%m-%d\') daily,count(1) count FROM _user \nWHERE gmt_create<=NOW() GROUP BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\');', 'batch€__user_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\')', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (17, '_user_daily', -1, '每日门店新增客户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id, DATE_FORMAT(gmt_create,\'%Y-%m-%d\') daily,count(1) count FROM _user \nWHERE gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) GROUP BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\');', 'select 1 from _user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\'', '', '', 0, '1', '', '2021-11-15 14:59:02', '2021-11-15 14:59:02', 0);
INSERT INTO `simple_job` VALUES (18, '_pet_daily_init', 0, '宠物身份证绑定趋势', 'auto_mysql', 'oldmain', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily, count(1)count FROM _pet  \nWHERE gmt_create<=NOW() GROUP BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'batch€__pet_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\')', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (19, '_pet_daily', -1, '宠物身份证绑定趋势', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily, count(1)count FROM _pet  \nWHERE  gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) GROUP BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'select 1 from _pet_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\'', '', '', 0, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (21, '_recharge_order_daily_init', 0, '每日首充用户', 'auto_mysql', 'oldmain', 'SELECT tenant_id,count(user_id)count,daily FROM(\nSELECT tenant_id,user_id,DATE_FORMAT(MIN(gmt_create),\'%Y-%m-%d\') daily FROM _recharge_order \nWHERE gmt_create<=NOW() GROUP BY user_id\n)a GROUP BY tenant_id,daily', 'batch€__recharge_order_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\')', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (22, '_recharge_order_daily', -1, '每日首充用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,count(user_id)count,daily FROM(\nSELECT tenant_id,user_id,DATE_FORMAT(MIN(gmt_create),\'%Y-%m-%d\') daily FROM _recharge_order \nWHERE gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) GROUP BY user_id\n)a GROUP BY tenant_id,daily', 'select 1 from _recharge_order_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\'', '', '', 0, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (23, '_order_daily_base_init', 0, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain', 'SELECT  tenant_id,order_source,order_type,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,count(1) count, SUM(pay_price)pay_price, \'base\'table_source\nFROM _base_order WHERE gmt_create<=NOW() AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500) AND order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY tenant_id,order_source,order_type, DATE_FORMAT(gmt_create,\'%Y-%m-%d\')ORDER BY tenant_id,order_source,order_type\n', 'batch€__order_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') AND order_type!=\'GOODS\'', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (24, '_order_daily_base', -1, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain,store', 'SELECT  tenant_id,order_source,order_type,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,count(1) count, SUM(pay_price)pay_price,\'base\'table_source\nFROM _base_order WHERE  gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500) AND order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY tenant_id,order_source,order_type, DATE_FORMAT(gmt_create,\'%Y-%m-%d\')ORDER BY tenant_id,order_source,order_type\n', 'select 1 from _order_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and order_source=\'#order_source#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 0, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (25, '_order_daily_goods_init', 0, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain', 'SELECT  tenant_id,\'MP\'order_source,\'GOODS\'order_type,DATE_FORMAT(gmt_create,\'%Y-%m-%d\') daily,count(1) count, SUM(pay_price)pay_price,\'goods\'table_source\nFROM _order WHERE gmt_create<=NOW()\nAND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id, DATE_FORMAT(gmt_create,\'%Y-%m-%d\')ORDER BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'batch€__order_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') AND order_type=\'GOODS\'', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (26, '_order_daily_goods', -1, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain,store', 'SELECT  tenant_id,\'MP\'order_source,\'GOODS\'order_type,DATE_FORMAT(gmt_create,\'%Y-%m-%d\') daily,count(1) count, SUM(pay_price)pay_price,\'goods\'table_source\nFROM _order WHERE gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY)\nAND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id, DATE_FORMAT(gmt_create,\'%Y-%m-%d\')ORDER BY tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and order_source=\'#order_source#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 0, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (27, '_order_daily_crs_init', 0, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain', 'SELECT  o.tenant_id,\'CRS\'order_source,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily,count(1) count, SUM(o.actual_amount)pay_price,\'crs\'table_source\nFROM _crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nWHERE o.gmt_create<=NOW() AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY o.tenant_id,s.type, DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'batch€__order_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') AND order_type=\'GOODS\'', '', '', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (28, '_order_daily_crs', -1, '按日按门店维度的订单总数,总价', 'auto_mysql', 'oldmain,store', 'SELECT  o.tenant_id,\'CRS\'order_source,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily,count(1) count, SUM(o.actual_amount)pay_price,\'crs\'table_source\nFROM _crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nWHERE o.gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY o.tenant_id,s.type, DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and order_source=\'#order_source#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 0, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (29, '_group_buying', -1, '区域集采平台排行', 'section_value', 'datacenter', 'SELECT id,tenant_ids FROM _group_buying WHERE is_del=0', '', '', '', 1, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (30, '_group_buying', -1, '区域集采平台排行', 'mysql', 'datacenter', 'SELECT #id# id, SUM(u.count)user_count FROM _user_daily u WHERE tenant_id IN (#tenant_ids#)', 'SELECT 1', 'update _group_buying set user_count=#user_count# where id=#id#', '', 2, '1', '', '2021-11-15 14:59:03', '2021-11-15 14:59:03', 0);
INSERT INTO `simple_job` VALUES (31, '_group_buying', -1, '区域集采平台排行', 'mysql', 'datacenter', 'SELECT #id# id, CONVERT(SUM(u.pay_price),SIGNED)pay_price,SUM(u.count)order_count FROM _order_daily u WHERE tenant_id IN (#tenant_ids#)', 'SELECT 1', 'update _group_buying set pay_price=#pay_price#,order_count=#order_count# where id=#id#', '', 3, '1', '', '2021-11-17 16:59:19', '2021-11-17 16:59:19', 0);
INSERT INTO `simple_job` VALUES (32, '_order_sell_daily_goods_init', 0, '商品销售情况', 'auto_mysql', 'oldmain', 'SELECT \'goods\'table_source,\'GOODS\'order_type,c.title category_title,o.tenant_id,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(s.spu_id)count,count(DISTINCT o.user_id)user_count FROM \n_order o INNER JOIN _order_sku s ON o.order_no=s.order_no\nINNER JOIN _spu spu ON spu.id=s.spu_id\nINNER JOIN _category c ON c.id=spu.category_id\nWHERE o.gmt_create<=NOW() AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'batch€__order_sell_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') and table_source=\'goods\'', '', '', 1, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (33, '_order_sell_daily_goods', -1, '商品销售情况', 'auto_mysql', 'oldmain,store', 'SELECT \'goods\'table_source,\'GOODS\'order_type,c.title category_title,o.tenant_id,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(s.spu_id)count,count(DISTINCT o.user_id)user_count FROM \n_order o INNER JOIN _order_sku s ON o.order_no=s.order_no\nINNER JOIN _spu spu ON spu.id=s.spu_id\nINNER JOIN _category c ON c.id=spu.category_id\nWHERE o.gmt_create > DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_sell_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and spu_id=\'#spu_id#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 1, '1', '', '2021-11-15 16:23:01', '2021-11-15 16:23:01', 0);
INSERT INTO `simple_job` VALUES (34, '_order_sell_daily_base_init', 0, '商品销售情况', 'auto_mysql', 'oldmain', 'SELECT \'base\'table_source,o.tenant_id,o.order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_base_order o INNER JOIN _base_order_sku s ON o.order_no=s.order_no\nWHERE o.gmt_create<=NOW() AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND o.order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')\n', 'batch€__order_sell_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') and table_source=\'base\'', '', '', 1, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (35, '_order_sell_daily_base', -1, '商品销售情况', 'auto_mysql', 'oldmain,store', 'SELECT \'base\'table_source,o.tenant_id,o.order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_base_order o INNER JOIN _base_order_sku s ON o.order_no=s.order_no\nWHERE o.gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND o.order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_sell_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and spu_id=\'#spu_id#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 1, '1', '', '2021-11-16 14:40:33', '2021-11-16 14:40:33', 0);
INSERT INTO `simple_job` VALUES (36, '_order_sell_daily_crs_a_init', 0, '商品销售情况', 'auto_mysql', 'oldmain', 'SELECT \'crs\'table_source,o.tenant_id,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nWHERE o.gmt_create<=NOW() AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND s.type=\'SERVICE\'\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'batch€__order_sell_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') and table_source=\'crs\'', '', '', 1, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (37, '_order_sell_daily_crs_g_init', 0, '商品销售情况', 'auto_mysql', 'oldmain', 'SELECT c.title category_title,\'crs\'table_source,o.tenant_id,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nINNER JOIN _spu spu ON spu.id=s.spu_id\nINNER JOIN _category c ON c.id=spu.category_id\nWHERE o.gmt_create<=NOW() AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND s.type=\'GOODS\'\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'batch€__order_sell_daily_€where daily<=DATE_FORMAT(NOW(),\'%Y-%m-%d\') and table_source=\'crs\'', '', '', 1, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (38, '_order_sell_daily_crs_a', -1, '商品销售情况', 'auto_mysql', 'oldmain,store', 'SELECT \'crs\'table_source,o.tenant_id,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nWHERE o.gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND s.type=\'SERVICE\'\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_sell_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and spu_id=\'#spu_id#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 1, '1', '', '2021-11-16 14:40:26', '2021-11-16 14:40:26', 0);
INSERT INTO `simple_job` VALUES (39, '_order_sell_daily_crs_g', -1, '商品销售情况', 'auto_mysql', 'oldmain,store', 'SELECT c.title category_title,\'crs\'table_source,o.tenant_id,IF(s.type=\'SERVICE\',\'APPOINT\',s.type) order_type,s.spu_title,s.title,s.spu_id,s.sku_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')daily, count(1)count,count(DISTINCT o.user_id)user_count FROM \n_crs_order o INNER JOIN _crs_order_sku s ON o.id=s.order_id\nINNER JOIN _spu spu ON spu.id=s.spu_id\nINNER JOIN _category c ON c.id=spu.category_id\nWHERE o.gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND o.`status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nAND s.type=\'GOODS\'\nGROUP BY o.tenant_id,s.spu_id,DATE_FORMAT(o.gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_sell_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and spu_id=\'#spu_id#\' and order_type=\'#order_type#\' and table_source=\'#table_source#\'', '', '', 1, '1', '', '2021-11-16 14:40:21', '2021-11-16 14:40:21', 0);
INSERT INTO `simple_job` VALUES (40, '_order_user_daily_base_init', 0, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _base_order\nWHERE gmt_create<=NOW() AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500) AND order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', 'UPDATE _order_user_daily SET tenant_id=\'#tenant_id#\',daily=\'#daily#\',user_id=\'#user_id#\' WHERE id = ( SELECT a.id FROM ( SELECT id FROM _order_user_daily WHERE  daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\' LIMIT 1 )a)', 'INSERT INTO _order_user_daily(tenant_id,daily,user_id)VALUES(\'#tenant_id#\',\'#daily#\',\'#user_id#\')', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (41, '_order_user_daily_base', -1, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _base_order\nWHERE gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500) AND order_type IN (\'GOODS\', \'BOARD\',\'APPOINT\')\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', '', '', 0, '1', '', '2021-11-16 14:39:54', '2021-11-16 14:39:54', 0);
INSERT INTO `simple_job` VALUES (42, '_order_user_daily_goods_init', 0, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _order\nWHERE gmt_create<=NOW() AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', 'UPDATE _order_user_daily SET tenant_id=\'#tenant_id#\',daily=\'#daily#\',user_id=\'#user_id#\' WHERE id = ( SELECT a.id FROM ( SELECT id FROM _order_user_daily WHERE  daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\' LIMIT 1 )a)', 'INSERT INTO _order_user_daily(tenant_id,daily,user_id)VALUES(\'#tenant_id#\',\'#daily#\',\'#user_id#\')', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (43, '_order_user_daily_goods', -1, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _order\nWHERE gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY)  AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', '', '', 0, '1', '', '2021-11-16 14:40:03', '2021-11-16 14:40:03', 0);
INSERT INTO `simple_job` VALUES (44, '_order_user_daily_crs_init', 0, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _crs_order\nWHERE gmt_create<=NOW() AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', 'UPDATE _order_user_daily SET tenant_id=\'#tenant_id#\',daily=\'#daily#\',user_id=\'#user_id#\' WHERE id = ( SELECT a.id FROM ( SELECT id FROM _order_user_daily WHERE  daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\' LIMIT 1 )a)', 'INSERT INTO _order_user_daily(tenant_id,daily,user_id)VALUES(\'#tenant_id#\',\'#daily#\',\'#user_id#\')', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (45, '_order_user_daily_crs', -1, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _crs_order\nWHERE gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', '', '', 0, '1', '', '2021-11-16 14:40:09', '2021-11-16 14:40:09', 0);
INSERT INTO `simple_job` VALUES (46, '_order_user_daily_recharge_init', 0, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _recharge_order\nWHERE gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', 'UPDATE _order_user_daily SET tenant_id=\'#tenant_id#\',daily=\'#daily#\',user_id=\'#user_id#\' WHERE id = ( SELECT a.id FROM ( SELECT id FROM _order_user_daily WHERE  daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\' LIMIT 1 )a)', 'INSERT INTO _order_user_daily(tenant_id,daily,user_id)VALUES(\'#tenant_id#\',\'#daily#\',\'#user_id#\')', 0, '1', '', '2021-11-17 17:59:43', '2021-11-17 17:59:43', 0);
INSERT INTO `simple_job` VALUES (47, '_order_user_daily_recharge', -1, '活跃用户', 'auto_mysql', 'oldmain,store', 'SELECT tenant_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')daily,user_id\nFROM _recharge_order\nWHERE gmt_create>DATE_SUB(CURDATE(), INTERVAL 7 DAY) AND `status` IN (20,30,40,50,2100,2200,2300,2400,150,200,400,500)\nGROUP BY tenant_id,user_id,DATE_FORMAT(gmt_create,\'%Y-%m-%d\')\n', 'select 1 from _order_user_daily where daily=\'#daily#\' and tenant_id=\'#tenant_id#\' and user_id=\'#user_id#\'', '', '', 0, '1', '', '2021-11-16 16:49:42', '2021-11-16 16:49:42', 0);
INSERT INTO `simple_job` VALUES (48, '_tenant_daily', -1, '租户', 'auto_mysql', 'oldmain,store', 'SELECT id,\n  name,\n  address,\n  wx_mini_appid,\n  wx_mini_secret,\n  wx_mch_id,\n  wx_mch_key,\n  wx_cert_path,\n  alipay_account,\n  alipay_app_auth_token,\n  gmt_create,\n  gmt_update,\n  credit_code,\n  sms_count,\n  contact_mobile,\n  sms_total_num,\n  sms_give_num,\n  sms_error_num,\nIFNULL(legal_person,\'\')legal_person,\n  sms_success_num,\n  trial_version FROM _tenant\n\n', 'select 1 from _tenant_daily where id=\'#id#\'', '', '', 0, '1', '', '2021-11-18 11:13:31', '2021-11-18 11:13:31', 0);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
